site_name: WeatherFlow Documentation
site_description: Documentation for the WeatherFlow weather prediction library
theme:
  name: material
  palette:
    primary: blue
    accent: orange
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - search.highlight

nav:
  - Home: index.md
  - Installation: installation.md
  - Getting Started: getting_started.md
  - Tutorials:
      - Quick Start: tutorials/quickstart.md
      - Working with ERA5: tutorials/era5.md
      - Custom Physics Workflows: tutorials/physics.md
  - Advanced Usage: advanced_usage.md
  - Flow Matching Primer: flow_matching.md
  - Advanced Topics:
      - Continuous Normalizing Flows: advanced_topics/continuous_normalizing_flows.md
      - Implementation Guide: advanced_topics/flow_matching_implementation.md
  - API Reference:
      - Data Loading: api/data.md
      - Models: api/models.md
      - Training: api/training.md
      - Solvers and Paths: api/solvers.md
      - Utilities and Visualization: api/visualization.md
  - Examples: examples.md
  - Release Notes: release_notes.md
  - Blog:
      - ERA5 Flow Matching Pipeline: blog/era5-flow-pipeline.md
      - Visualising Flow Matching Forecasts: blog/flow-matching-visualization.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - admonition
  - footnotes

repo_url: https://github.com/yourusername/weatherflow
