import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
function ModelConfigurator({ value, onChange }) {
    const handleNumberChange = (event) => {
        const { name, value: raw } = event.target;
        onChange({ ...value, [name]: Number(raw) });
    };
    const handleToggle = (event) => {
        const { name, checked } = event.target;
        onChange({ ...value, [name]: checked });
    };
    return (_jsxs("section", { className: "section-card", children: [_jsxs("div", { children: [_jsx("h2", { children: "Model architecture" }), _jsx("p", { children: "Configure the WeatherFlowMatch backbone used for the experiment." })] }), _jsxs("div", { className: "form-grid", children: [_jsxs("label", { children: ["Backbone", _jsxs("select", { name: "backbone", value: value.backbone, onChange: (e) => onChange({ ...value, backbone: e.target.value }), children: [_jsx("option", { value: "grid", children: "Lat/Lon Grid" }), _jsx("option", { value: "icosahedral", children: "Icosahedral Mesh" })] })] }), _jsxs("label", { children: ["Subdivisions (icosahedral)", _jsx("input", { type: "number", min: 0, max: 3, name: "subdivisions", value: value.subdivisions, onChange: handleNumberChange })] }), _jsxs("label", { children: ["Interp cache dir (optional)", _jsx("input", { type: "text", name: "interpCacheDir", value: value.interpCacheDir ?? '', onChange: (e) => onChange({ ...value, interpCacheDir: e.target.value || null }) })] }), _jsxs("label", { children: ["Hidden dimension", _jsx("input", { type: "number", min: 32, max: 512, name: "hiddenDim", value: value.hiddenDim, onChange: handleNumberChange })] }), _jsxs("label", { children: ["Layers", _jsx("input", { type: "number", min: 1, max: 8, name: "nLayers", value: value.nLayers, onChange: handleNumberChange })] }), _jsxs("label", { children: ["Attention window", _jsx("input", { type: "number", min: 0, max: 64, name: "windowSize", value: value.windowSize, onChange: handleNumberChange })] }), _jsxs("label", { className: "checkbox-row", children: [_jsx("input", { type: "checkbox", name: "useAttention", checked: value.useAttention, onChange: handleToggle }), "Use multi-head attention"] }), _jsxs("label", { className: "checkbox-row", children: [_jsx("input", { type: "checkbox", name: "physicsInformed", checked: value.physicsInformed, onChange: handleToggle }), "Apply physics constraints"] }), _jsxs("label", { className: "checkbox-row", children: [_jsx("input", { type: "checkbox", name: "sphericalPadding", checked: value.sphericalPadding, onChange: handleToggle }), "Use spherical padding (wrap longitude)"] }), _jsxs("label", { className: "checkbox-row", children: [_jsx("input", { type: "checkbox", name: "useGraphMp", checked: value.useGraphMp, onChange: handleToggle }), "Enable graph message passing (wrapped grid)"] })] })] }));
}
export default ModelConfigurator;
